[package]
name = "appim"
version = "1.0.0"
edition = "2023" 
description="A simple cli tool to create desktop entry from AppImage" 
authors = ["@khuongduy354"]
repository="https://github.com/khuongduy354/appim"
readme="readme.md"


[dependencies]
clap = { version = "4.3.1", features = ["derive"] }
